/* tslint:disable */
/* eslint-disable */
/**
 * OTT API
 * 동영상 OTT 서비스 API 문서
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface UserDto
 */
export interface UserDto {
    /**
     * 회원 고유번호
     * @type {number}
     * @memberof UserDto
     */
    'id'?: number;
    /**
     * 회원 로그인 ID
     * @type {string}
     * @memberof UserDto
     */
    'username'?: string;
    /**
     * 별명/이름
     * @type {string}
     * @memberof UserDto
     */
    'displayName'?: string;
    /**
     * 권한
     * @type {string}
     * @memberof UserDto
     */
    'role'?: string;
    /**
     * 가입일(ISO8601)
     * @type {string}
     * @memberof UserDto
     */
    'createdAt'?: string;
}
/**
 * 
 * @export
 * @interface UserLoginRequest
 */
export interface UserLoginRequest {
    /**
     * 로그인 ID
     * @type {string}
     * @memberof UserLoginRequest
     */
    'username': string;
    /**
     * 비밀번호
     * @type {string}
     * @memberof UserLoginRequest
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface UserSignupRequest
 */
export interface UserSignupRequest {
    /**
     * 로그인 ID
     * @type {string}
     * @memberof UserSignupRequest
     */
    'username': string;
    /**
     * 비밀번호(8~30자)
     * @type {string}
     * @memberof UserSignupRequest
     */
    'password': string;
    /**
     * 별명
     * @type {string}
     * @memberof UserSignupRequest
     */
    'displayName': string;
}
/**
 * 
 * @export
 * @interface VideoDto
 */
export interface VideoDto {
    /**
     * 동영상 고유번호(PK)
     * @type {number}
     * @memberof VideoDto
     */
    'id'?: number;
    /**
     * 동영상 제목
     * @type {string}
     * @memberof VideoDto
     */
    'title': string;
    /**
     * 동영상 설명
     * @type {string}
     * @memberof VideoDto
     */
    'description'?: string;
    /**
     * 썸네일 이미지 URL
     * @type {string}
     * @memberof VideoDto
     */
    'thumbnailUrl'?: string;
    /**
     * 동영상 재생 시간(초)
     * @type {number}
     * @memberof VideoDto
     */
    'playTime'?: number;
    /**
     * 업로드한 회원 ID
     * @type {string}
     * @memberof VideoDto
     */
    'uploadUserId'?: string;
    /**
     * 업로드 일시(ISO8601)
     * @type {string}
     * @memberof VideoDto
     */
    'createdAt'?: string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * JWT 인증 후 내 정보를 조회합니다.
         * @summary 내 정보 조회
         * @param {string} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyInfo: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('getMyInfo', 'authorization', authorization)
            const localVarPath = `/api/users/my-info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 동영상 ID로 특정 동영상을 조회합니다.
         * @summary 동영상 상세 조회
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVideoDetail: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getVideoDetail', 'id', id)
            const localVarPath = `/api/videos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 등록된 모든 동영상을 최신순으로 조회합니다.
         * @summary 동영상 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVideoList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/videos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 로그인 성공시 JWT 토큰을 반환합니다.
         * @summary 로그인
         * @param {UserLoginRequest} userLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (userLoginRequest: UserLoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userLoginRequest' is not null or undefined
            assertParamExists('login', 'userLoginRequest', userLoginRequest)
            const localVarPath = `/api/users/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userLoginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 신규 회원을 등록합니다.
         * @summary 회원가입
         * @param {UserSignupRequest} userSignupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signup: async (userSignupRequest: UserSignupRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userSignupRequest' is not null or undefined
            assertParamExists('signup', 'userSignupRequest', userSignupRequest)
            const localVarPath = `/api/users/signup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userSignupRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * HTTP Range를 지원하는 동영상 스트리밍 API 입니다.
         * @summary 동영상 스트리밍
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        streamVideo: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('streamVideo', 'id', id)
            const localVarPath = `/api/videos/file/stream/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 동영상 파일과 메타데이터를 업로드하고 DB에 등록합니다.
         * @summary 동영상 파일 업로드
         * @param {string} title 
         * @param {string} userId 
         * @param {File} file 
         * @param {string} [description] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadVideo: async (title: string, userId: string, file: File, description?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'title' is not null or undefined
            assertParamExists('uploadVideo', 'title', title)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('uploadVideo', 'userId', userId)
            // verify required parameter 'file' is not null or undefined
            assertParamExists('uploadVideo', 'file', file)
            const localVarPath = `/api/videos/file/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (title !== undefined) {
                localVarQueryParameter['title'] = title;
            }

            if (description !== undefined) {
                localVarQueryParameter['description'] = description;
            }

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * JWT 인증 후 내 정보를 조회합니다.
         * @summary 내 정보 조회
         * @param {string} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyInfo(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyInfo(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getMyInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 동영상 ID로 특정 동영상을 조회합니다.
         * @summary 동영상 상세 조회
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVideoDetail(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VideoDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getVideoDetail(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getVideoDetail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 등록된 모든 동영상을 최신순으로 조회합니다.
         * @summary 동영상 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVideoList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<VideoDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getVideoList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getVideoList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 로그인 성공시 JWT 토큰을 반환합니다.
         * @summary 로그인
         * @param {UserLoginRequest} userLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(userLoginRequest: UserLoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(userLoginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 신규 회원을 등록합니다.
         * @summary 회원가입
         * @param {UserSignupRequest} userSignupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signup(userSignupRequest: UserSignupRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signup(userSignupRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.signup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * HTTP Range를 지원하는 동영상 스트리밍 API 입니다.
         * @summary 동영상 스트리밍
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async streamVideo(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.streamVideo(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.streamVideo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 동영상 파일과 메타데이터를 업로드하고 DB에 등록합니다.
         * @summary 동영상 파일 업로드
         * @param {string} title 
         * @param {string} userId 
         * @param {File} file 
         * @param {string} [description] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadVideo(title: string, userId: string, file: File, description?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadVideo(title, userId, file, description, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.uploadVideo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * JWT 인증 후 내 정보를 조회합니다.
         * @summary 내 정보 조회
         * @param {string} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyInfo(authorization: string, options?: RawAxiosRequestConfig): AxiosPromise<UserDto> {
            return localVarFp.getMyInfo(authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 동영상 ID로 특정 동영상을 조회합니다.
         * @summary 동영상 상세 조회
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVideoDetail(id: number, options?: RawAxiosRequestConfig): AxiosPromise<VideoDto> {
            return localVarFp.getVideoDetail(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 등록된 모든 동영상을 최신순으로 조회합니다.
         * @summary 동영상 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVideoList(options?: RawAxiosRequestConfig): AxiosPromise<Array<VideoDto>> {
            return localVarFp.getVideoList(options).then((request) => request(axios, basePath));
        },
        /**
         * 로그인 성공시 JWT 토큰을 반환합니다.
         * @summary 로그인
         * @param {UserLoginRequest} userLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(userLoginRequest: UserLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.login(userLoginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 신규 회원을 등록합니다.
         * @summary 회원가입
         * @param {UserSignupRequest} userSignupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signup(userSignupRequest: UserSignupRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserDto> {
            return localVarFp.signup(userSignupRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * HTTP Range를 지원하는 동영상 스트리밍 API 입니다.
         * @summary 동영상 스트리밍
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        streamVideo(id: number, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.streamVideo(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 동영상 파일과 메타데이터를 업로드하고 DB에 등록합니다.
         * @summary 동영상 파일 업로드
         * @param {string} title 
         * @param {string} userId 
         * @param {File} file 
         * @param {string} [description] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadVideo(title: string, userId: string, file: File, description?: string, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.uploadVideo(title, userId, file, description, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * JWT 인증 후 내 정보를 조회합니다.
     * @summary 내 정보 조회
     * @param {string} authorization 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getMyInfo(authorization: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getMyInfo(authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 동영상 ID로 특정 동영상을 조회합니다.
     * @summary 동영상 상세 조회
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getVideoDetail(id: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getVideoDetail(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 등록된 모든 동영상을 최신순으로 조회합니다.
     * @summary 동영상 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getVideoList(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getVideoList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 로그인 성공시 JWT 토큰을 반환합니다.
     * @summary 로그인
     * @param {UserLoginRequest} userLoginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public login(userLoginRequest: UserLoginRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).login(userLoginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 신규 회원을 등록합니다.
     * @summary 회원가입
     * @param {UserSignupRequest} userSignupRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public signup(userSignupRequest: UserSignupRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).signup(userSignupRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * HTTP Range를 지원하는 동영상 스트리밍 API 입니다.
     * @summary 동영상 스트리밍
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public streamVideo(id: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).streamVideo(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 동영상 파일과 메타데이터를 업로드하고 DB에 등록합니다.
     * @summary 동영상 파일 업로드
     * @param {string} title 
     * @param {string} userId 
     * @param {File} file 
     * @param {string} [description] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public uploadVideo(title: string, userId: string, file: File, description?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).uploadVideo(title, userId, file, description, options).then((request) => request(this.axios, this.basePath));
    }
}



